### PR TITLE
New snap service

### PR DESCRIPTION
**Pull request by lenaschoenburg**
This is a basic layout for the new snap service. I removed all `serverless`-related code to keep things simple first.

### CODE REVIEW

**Comment by lenaschoenburg** [comment]
I would like to extend this to support executing custom javascript before capturing screenshots. This would provide an easy way to add branding/customization to the finished PDF or PNG.

**Comment by lenaschoenburg** [comment]
The http endpoints are basically finished, but I'm having a hard time re-implementing the serverless side of things. Maybe someone from redash want's to take that over? @arikfr

**Comment by arikfr** [comment]
> I would like to extend this to support executing custom javascript before capturing screenshots. This would provide an easy way to add branding/customization to the finished PDF or PNG.

Executing when making a call to this service to make a screenshot? 

> The http endpoints are basically finished, but I'm having a hard time re-implementing the serverless side of things. Maybe someone from redash want's to take that over? @arikfr

Can you elaborate on what issues you're having?

**Comment by lenaschoenburg** [comment]
> Executing when making a call to this service to make a screenshot?

Yes, I have added this in the last commit.

> Can you elaborate on what issues you're having?

Basically lack of experience and testing environment. Setting up an AWS account, creating a redash instance that is reachable from AWS Lambda etc. I can continue to work on this if you don't have the resources, I just wanted to give you a fair warning that this is going to take me a bit of time.

**Comment by lenaschoenburg** [comment]
So I have added serverless again (not yet tested on Lambda, only locally). I have also switched over to webpack because that seemed to work better with serverless. The custom script execution broke again so I removed it. Could you give this a quick review and tell me if this is something that you would merge?

**Pull request closed without merging**
